In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

C:\Users\sahma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.1.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

In [61]:
df=pd.read_csv("dataset/train.csv")
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  12000 non-null  int64
 1   blue           12000 non-null  int64
 2   clock_speed    12000 non-null  float64
 3   dual_sim       12000 non-null  int64
 4   fc             12000 non-null  int64
 5   four_g         12000 non-null  int64
 6   int_memory     12000 non-null  int64
 7   m_dep          12000 non-null  float64
 8   mobile_wt      12000 non-null  int64
 9   n_cores        12000 non-null  int64
 10  pc             12000 non-null  int64
 11  px_height      12000 non-null  int64
 12  px_width       12000 non-null  int64
 13  ram            12000 non-null  int64
 14  sc_h           12000 non-null  int64
 15  sc_w           12000 non-null  int64
 16  talk_time      12000 non-null  int64
 17  three_g        12000 non-null  int64
 18  touch_screen   12000 non-null  int64
 19  wifi           12000 non-null  int64
 20  price_range    12000 non-null  int64
dtypes: float64(2), int64(19)
memory usage: 1.9 MB

In [63]:
df.isna()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [64]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.00000,...,12000.000000,12000.000000,12000.000000,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,1238.518500,0.495000,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.52050,...,645.108000,1251.515500,2124.213000,12.306500,5.76700,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.326643,0.499996,0.815834,0.499931,4.340539,0.499558,18.141934,0.288355,35.392279,2.28736,...,443.688339,432.109389,1084.506015,4.212367,4.35549,5.462817,0.426184,0.500012,0.499972,1.118081
min,501.000000,0.000000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.00000,...,0.000000,500.000000,256.000000,5.000000,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.000000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.00000,...,282.750000,874.750000,1207.500000,9.000000,2.00000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.000000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.00000,...,564.000000,1247.000000,2146.500000,12.000000,5.00000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.000000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.00000,...,947.250000,1633.000000,3064.500000,16.000000,9.00000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.000000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.00000,...,1960.000000,1998.000000,3998.000000,19.000000,18.00000,20.000000,1.000000,1.000000,1.000000,3.000000

In [65]:
x=df.iloc[:, 0:-1].values
y=df.iloc[:, -1].values

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [67]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [68]:
model=tf.keras.models.Sequential()

In [69]:
model.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [70]:
model.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [71]:
model.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [72]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [73]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [74]:
model.fit(X_train, y_train, batch_size=32, epochs=25)

Epoch 1/25
300/300 [==============================] - 2s 3ms/step - loss: 0.3388 - accuracy: 0.2571
Epoch 2/25
300/300 [==============================] - 1s 3ms/step - loss: -9.6809 - accuracy: 0.2504
Epoch 3/25
300/300 [==============================] - 1s 3ms/step - loss: -135.9339 - accuracy: 0.2504
Epoch 4/25
300/300 [==============================] - 1s 3ms/step - loss: -706.4717 - accuracy: 0.2504
Epoch 5/25
300/300 [==============================] - 1s 3ms/step - loss: -2143.3389 - accuracy: 0.2504
Epoch 6/25
300/300 [==============================] - 1s 3ms/step - loss: -4856.0508 - accuracy: 0.2504
Epoch 7/25
300/300 [==============================] - 1s 3ms/step - loss: -9224.9414 - accuracy: 0.2504
Epoch 8/25
300/300 [==============================] - 1s 3ms/step - loss: -15648.7646 - accuracy: 0.2504
Epoch 9/25
300/300 [==============================] - 1s 3ms/step - loss: -24525.8203 - accuracy: 0.2504
Epoch 10/25
300/300 [==============================] - 1s 3ms/step - loss: -36228.0742 - accuracy: 0.2504
Epoch 11/25
300/300 [==============================] - 1s 3ms/step - loss: -51079.7969 - accuracy: 0.2504
Epoch 12/25
300/300 [==============================] - 1s 3ms/step - loss: -69376.4375 - accuracy: 0.2504
Epoch 13/25
300/300 [==============================] - 1s 3ms/step - loss: -91508.3516 - accuracy: 0.2504
Epoch 14/25
300/300 [==============================] - 1s 3ms/step - loss: -117842.1719 - accuracy: 0.2504
Epoch 15/25
300/300 [==============================] - 1s 3ms/step - loss: -148754.1875 - accuracy: 0.2504
Epoch 16/25
300/300 [==============================] - 1s 3ms/step - loss: -184646.5938 - accuracy: 0.2504
Epoch 17/25
300/300 [==============================] - 1s 3ms/step - loss: -225839.0469 - accuracy: 0.2504
Epoch 18/25
300/300 [==============================] - 1s 3ms/step - loss: -272632.8125 - accuracy: 0.2504
Epoch 19/25
300/300 [==============================] - 1s 3ms/step - loss: -325430.0938 - accuracy: 0.2504
Epoch 20/25
300/300 [==============================] - 1s 3ms/step - loss: -384765.7188 - accuracy: 0.2504
Epoch 21/25
300/300 [==============================] - 1s 3ms/step - loss: -451002.8750 - accuracy: 0.2504
Epoch 22/25
300/300 [==============================] - 1s 3ms/step - loss: -524424.8750 - accuracy: 0.2504
Epoch 23/25
300/300 [==============================] - 1s 3ms/step - loss: -605541.6250 - accuracy: 0.2504
Epoch 24/25
300/300 [==============================] - 1s 3ms/step - loss: -694742.4375 - accuracy: 0.2504
Epoch 25/25
300/300 [==============================] - 1s 3ms/step - loss: -792432.3750 - accuracy: 0.2504

In [75]:
y_pred=model.predict(X_test)

75/75 [==============================] - 0s 2ms/step

In [76]:
y_pred=(y_pred>0.5)

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
cm

array([[  0, 619,   0,   0],
       [  0, 596,   0,   0],
       [  0, 561,   0,   0],
       [  0, 624,   0,   0]], dtype=int64)

In [78]:
accuracy_score(y_test, y_pred)

0.24833333333333332